# Machine Learning November Major Project
vamsi varma (vamsi.hansi@gmail.com)/(9133143689)

# Problem statement
Adult Salary Prediction->
Create a classification model to predict whether a person makes over $50k a
year.

In [70]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [71]:
df1 = pd.read_csv("adult.csv")
df1.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

# 1) Renaming The Columns.

In [72]:
"""Adding or Renaming the column Names on the top of the DataFrame"""

Attributes = ["Age","Workclass","Fnlwgt","Education","education_num","marital_status","occupation","relationship","race","sex","capital_gain","capital_loss","hours_per_week","native_country","income"]

if(Attributes!=df1.columns.values.tolist()):
    DataDict=dict(zip(Attributes,df1.columns.values.tolist()))

Adding_row = []

Adding_row.insert(0,DataDict)

df1.set_axis(["Age","Workclass","Fnlwgt","Education","education_num","marital_status","occupation","relationship","race","sex","capital_gain","capital_loss","hours_per_week","native_country","income"], axis='columns', inplace=True)

Df = pd.concat([pd.DataFrame(Adding_row), df1], ignore_index=True)

cd={"Age":int,"Fnlwgt":int,"education_num":int,"capital_gain":int,"capital_loss":int,"hours_per_week":int}

Df=Df.astype(cd)

Df


Age          Workclass  Fnlwgt    Education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [73]:
Df.shape

(32561, 15)

# 2) Removing or Handling Null Values (if any).

In [74]:
Df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

 """Therefore their are no null values."""

# Handling Duplicates (if any).

In [75]:
Df.duplicated().sum()

24

"Here, We are having 24 Null values so we need to remove them."

In [76]:
"""Handling the duplicates"""
Df.drop_duplicates(inplace=True)

print(Df.duplicated().sum()) #Checking Still we are having duplicates or not.

print(Df.shape) #Checking the shape if any changes are occured or not in the dataframe.



0
(32537, 15)


# Handling the missing values.

'''As we can see In the given adult.CSV file we are having some of the Missing values like "?" So we need to Handle them.'''

In [77]:
Df.dtypes

Age                int32
Workclass         object
Fnlwgt             int32
Education         object
education_num      int32
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int32
capital_loss       int32
hours_per_week     int32
native_country    object
income            object
dtype: object

In [78]:
"""Checking for Missing values."""

x=[i for i in Df.columns if Df[i].dtypes == "O" ]

for feature in x:
    print(Df[feature].value_counts()) 
    print("xxxxxxxxxxxxxxxxxxxxxxxxxxx")

 Private             22673
 Self-emp-not-inc     2540
 Local-gov            2093
 ?                    1836
 State-gov            1298
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: Workclass, dtype: int64
xxxxxxxxxxxxxxxxxxxxxxxxxxx
 HS-grad         10494
 Some-college     7282
 Bachelors        5353
 Masters          1722
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           645
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           332
 1st-4th           166
 Preschool          50
Name: Education, dtype: int64
xxxxxxxxxxxxxxxxxxxxxxxxxxx
 Married-civ-spouse       14970
 Never-married            10667
 Divorced                  4441
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: marital_status, dtype: int64
xxxxxxxxxxxxxx

In [79]:
"""In the above DataSet the columns having Missing Values are
    (workclass)--(occupation)--(native_country)"""


print("workclass       : ",(2093/32561)*100) #-> The percentage of Missing values in workclass.
print("occupation      : ",(1843/32561)*100) #-> The percentage of Missing values in occupation.
print("native-country  : ",(583/32561)*100)  #-> The percentage of Missing values in native-country.

workclass       :  6.427935259973588
occupation      :  5.660145572924664
native-country  :  1.7904855501980899


In [80]:
"""Here To Handle missing values we are having 3 methods 
   But, As per our DataSet the percentage of Missing values in each of the 3 columns mentioned above are very Less
   so we can replace the missing values with the value which is more frequently repeated in the Respective column."""
   #Most frequently repeated is nothing but mode of that particular column.

import warnings
warnings.filterwarnings('ignore')

Df["Workclass"] = Df['Workclass'].apply(str).str.replace('?', 'Private' )
Df['occupation'] = Df['occupation'].apply(str).str.replace('?', 'Prof-specialty' )
Df['native_country'] = Df['native_country'].apply(str).str.replace('?', 'United-States' )

In [81]:
Df.head(20)

Age          Workclass  Fnlwgt      Education  education_num  \
0    39          State-gov   77516      Bachelors             13   
1    50   Self-emp-not-inc   83311      Bachelors             13   
2    38            Private  215646        HS-grad              9   
3    53            Private  234721           11th              7   
4    28            Private  338409      Bachelors             13   
5    37            Private  284582        Masters             14   
6    49            Private  160187            9th              5   
7    52   Self-emp-not-inc  209642        HS-grad              9   
8    31            Private   45781        Masters             14   
9    42            Private  159449      Bachelors             13   
10   37            Private  280464   Some-college             10   
11   30          State-gov  141297      Bachelors             13   
12   23            Private  122272      Bachelors             13   
13   32            Private  205019     Assoc-acdm             12   
14   40            Private  121772      Assoc-voc             11   
15   34            Private  245487        7th-8th              4   
16   25   Self-emp-not-inc  176756        HS-grad              9   
17   32            Private  186824        HS-grad              9   
18   38            Private   28887           11th              7   
19   43   Self-emp-not-inc  292175        Masters             14   

            marital_status          occupation    relationship  \
0            Never-married        Adm-clerical   Not-in-family   
1       Married-civ-spouse     Exec-managerial         Husband   
2                 Divorced   Handlers-cleaners   Not-in-family   
3       Married-civ-spouse   Handlers-cleaners         Husband   
4       Married-civ-spouse      Prof-specialty            Wife   
5       Married-civ-spouse     Exec-managerial            Wife   
6    Married-spouse-absent       Other-service   Not-in-family   
7       Married-civ-spouse     Exec-managerial         Husband   
8            Never-married      Prof-specialty   Not-in-family   
9       Married-civ-spouse     Exec-managerial         Husband   
10      Married-civ-spouse     Exec-managerial         Husband   
11      Married-civ-spouse      Prof-specialty         Husband   
12           Never-married        Adm-clerical       Own-child   
13           Never-married               Sales   Not-in-family   
14      Married-civ-spouse        Craft-repair         Husband   
15      Married-civ-spouse    Transport-moving         Husband   
16           Never-married     Farming-fishing       Own-child   
17           Never-married   Machine-op-inspct       Unmarried   
18      Married-civ-spouse               Sales         Husband   
19                Divorced     Exec-managerial       Unmarried   

                   race      sex  capital_gain  capital_loss  hours_per_week  \
0                 White     Male          2174             0              40   
1                 White     Male             0             0              13   
2                 White     Male             0             0              40   
3                 Black     Male             0             0              40   
4                 Black   Female             0             0              40   
5                 White   Female             0             0              40   
6                 Black   Female             0             0              16   
7                 White     Male             0             0              45   
8                 White   Female         14084             0              50   
9                 White     Male          5178             0              40   
10                Black     Male             0             0              80   
11   Asian-Pac-Islander     Male             0             0              40   
12                White   Female             0             0              30   
13                Black     Male             0             0        

# Encoding The Labels (if any).

In [82]:
"""Encoding the Label column"""

from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()

Df["income"]=lb.fit_transform(Df["income"])

Df["Workclass"]=lb.fit_transform(Df["Workclass"])

Df["Education"]=lb.fit_transform(Df["Education"])

Df["marital_status"]=lb.fit_transform(Df["marital_status"])

Df["occupation"]=lb.fit_transform(Df["occupation"])

Df["relationship"]=lb.fit_transform(Df["relationship"])

Df["race"]=lb.fit_transform(Df["race"])

Df["sex"]=lb.fit_transform(Df["sex"])

Df["native_country"]=lb.fit_transform(Df["native_country"])

Df.head(20)

Age  Workclass  Fnlwgt  Education  education_num  marital_status  \
0    39          6   77516          9             13               4   
1    50          5   83311          9             13               2   
2    38          3  215646         11              9               0   
3    53          3  234721          1              7               2   
4    28          3  338409          9             13               2   
5    37          3  284582         12             14               2   
6    49          3  160187          6              5               3   
7    52          5  209642         11              9               2   
8    31          3   45781         12             14               4   
9    42          3  159449          9             13               2   
10   37          3  280464         15             10               2   
11   30          6  141297          9             13               2   
12   23          3  122272          9             13               4   
13   32          3  205019          7             12               4   
14   40          3  121772          8             11               2   
15   34          3  245487          5              4               2   
16   25          5  176756         11              9               4   
17   32          3  186824         11              9               4   
18   38          3   28887          1              7               2   
19   43          5  292175         12             14               0   

    occupation  relationship  race  sex  capital_gain  capital_loss  \
0            0             1     4    1          2174             0   
1            3             0     4    1             0             0   
2            5             1     4    1             0             0   
3            5             0     2    1             0             0   
4            9             5     2    0             0             0   
5            3             5     4    0             0             0   
6            7             1     2    0             0             0   
7            3             0     4    1             0             0   
8            9             1     4    0         14084             0   
9            3             0     4    1          5178             0   
10           3             0     2    1             0             0   
11           9             0     1    1             0             0   
12           0             3     4    0             0             0   
13          11             1     2    1             0             0   
14           2             0     1    1             0             0   
15          13             0     0    1             0             0   
16           4             3     4    1             0             0   
17           6             4     4    1             0             0   
18          11             0     4    1             0             0   
19           3             4     4    0             0             0   

    hours_per_week  native_country  income  
0               40              38       0  
1               13              38       0  
2               40              38       0  
3               40              38       0  
4               40               4       0  
5               40              38       0  
6               16              22       0  
7               45              38       1  
8               50              38       1  
9               40              38       1  
10              80              38       1  
11              40              18       1  
12              30              38       0  
13              50              38       0  
14              40              38       1  
15              45              25       0  
16              35              38       0  
17              40              38       0  
18              50              38       0  
19              45              38       1

"From the above DataFrame we can say that the required column values are Labeled Succesfully."

# 3) Spliting data into training and test data.

In [83]:
x=Df.drop("income",axis=1) #data frame x --> independent.
y=Df["income"] #series y --> dependent.
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)


<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(32537, 14)
(32537,)


In [84]:
#<------spliting the data into train and test------>

from sklearn.model_selection import train_test_split

"""Spliting the Training Data and Test Data with test size of 30% from total size"""
                            
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

x1_train,x1_test,y1_train,y1_test=train_test_split(x,y,test_size=0.80,random_state=42)



"""Splited the Data Succesfully."""

In [85]:
 """Generating confusion matrix,Classification report and accuracy"""
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
def eval_model(y_test,ypred):
    print("\nConfusion Matrix : \n",confusion_matrix(y_test,ypred))
    print("\nClassification Report : \n",classification_report(y_test,ypred))
    print("\nAccuracy Score : ",accuracy_score(y_test,ypred))
def mscore(model):
    print("\nTraining Score for Training Data",model.score(x_train,y_train))
    print("\nTraining Score for Testing Data",model.score(x_test,y_test))


# 4,5) Applying the following models on the training dataset and generating the predicted value for the test data.


# a. Decision Tree Model ->

In [86]:
from sklearn.tree import DecisionTreeClassifier

Dtc= DecisionTreeClassifier(criterion="gini",max_depth=40,min_samples_split=15)

Dtc.fit(x_train,y_train)

ypredDTC=Dtc.predict(x_test)

print("Predicted value for test data in Decision Tree Model Classifier is :\n",ypredDTC)

eval_model(y_test,ypredDTC)

mscore(Dtc)

Predicted value for test data in Decision Tree Model Classifier is :
 [1 0 0 ... 0 0 0]

Confusion Matrix : 
 [[6609  796]
 [ 979 1378]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.87      0.89      0.88      7405
           1       0.63      0.58      0.61      2357

    accuracy                           0.82      9762
   macro avg       0.75      0.74      0.74      9762
weighted avg       0.81      0.82      0.82      9762


Accuracy Score :  0.8181725056340914

Training Score for Training Data 0.9287376509330406

Training Score for Testing Data 0.8181725056340914


# b. Random Forest Classifier ->

In [87]:
from sklearn.ensemble import RandomForestClassifier

Rfc= RandomForestClassifier(n_estimators=65,criterion="gini",max_depth=28,min_samples_split=15)

Rfc.fit(x_train,y_train)

ypredRFC=Rfc.predict(x_test)

print("Predicted value for test data in Random Forest Classifier is :\n",ypredRFC)

eval_model(y_test,ypredRFC)

mscore(Rfc)

Predicted value for test data in Random Forest Classifier is :
 [0 0 0 ... 0 0 0]

Confusion Matrix : 
 [[6959  446]
 [ 900 1457]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.89      0.94      0.91      7405
           1       0.77      0.62      0.68      2357

    accuracy                           0.86      9762
   macro avg       0.83      0.78      0.80      9762
weighted avg       0.86      0.86      0.86      9762


Accuracy Score :  0.8621184183568941

Training Score for Training Data 0.9243029637760702

Training Score for Testing Data 0.8621184183568941


# c. Logistic Regression ->

In [88]:
from sklearn.linear_model import LogisticRegression

logreg=LogisticRegression(solver='newton-cg',max_iter=1000)

logreg.fit(x_train,y_train)

ypredLR=logreg.predict(x_test)

print("Predicted value for test data in Logistic Regression is :\n",ypredLR)

eval_model(y_test,ypredLR)

mscore(logreg)


Predicted value for test data in Logistic Regression is :
 [0 0 0 ... 0 0 0]

Confusion Matrix : 
 [[6958  447]
 [1258 1099]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.85      0.94      0.89      7405
           1       0.71      0.47      0.56      2357

    accuracy                           0.83      9762
   macro avg       0.78      0.70      0.73      9762
weighted avg       0.81      0.83      0.81      9762


Accuracy Score :  0.8253431673837328

Training Score for Training Data 0.8234467618002196

Training Score for Testing Data 0.8253431673837328


# d. KNN Classifier ->

In [89]:
from sklearn.neighbors import KNeighborsClassifier

Knn=KNeighborsClassifier(n_neighbors=11)

Knn.fit(x_train,y_train)

ypredKNN=Knn.predict(x_test)

print("Predicted value for test data in KNN Classifier is :\n",ypredKNN)

eval_model(y_test,ypredKNN)

mscore(Knn)

Predicted value for test data in KNN Classifier is :
 [0 0 1 ... 0 0 0]

Confusion Matrix : 
 [[7132  273]
 [1761  596]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.80      0.96      0.88      7405
           1       0.69      0.25      0.37      2357

    accuracy                           0.79      9762
   macro avg       0.74      0.61      0.62      9762
weighted avg       0.77      0.79      0.75      9762


Accuracy Score :  0.791641057160418

Training Score for Training Data 0.8097036223929748

Training Score for Testing Data 0.791641057160418


# e. SVC Classifier (with linear kernel) ->

In [90]:
from sklearn.svm import SVC

Svm=SVC(kernel="linear",C=1)

Svm.fit(x1_train,y1_train)

ypredSVM=Svm.predict(x1_test)

print("Predicted value for test data in SVC Classifier is :\n",ypredSVM)

eval_model(y1_test,ypredSVM)

mscore(Svm)

Predicted value for test data in SVC Classifier is :
 [0 0 1 ... 0 0 0]

Confusion Matrix : 
 [[18883   863]
 [ 4459  1825]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.81      0.96      0.88     19746
           1       0.68      0.29      0.41      6284

    accuracy                           0.80     26030
   macro avg       0.74      0.62      0.64     26030
weighted avg       0.78      0.80      0.76     26030


Accuracy Score :  0.7955436035343834

Training Score for Training Data 0.7953018660812294

Training Score for Testing Data 0.7971727105101414


# 6) Computing Confusion matrix and classification report for each of these models.

# a. Decision Tree

In [91]:
"""Confusion Matrix and Classification report"""
eval_model(y_test,ypredDTC)


Confusion Matrix : 
 [[6609  796]
 [ 979 1378]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.87      0.89      0.88      7405
           1       0.63      0.58      0.61      2357

    accuracy                           0.82      9762
   macro avg       0.75      0.74      0.74      9762
weighted avg       0.81      0.82      0.82      9762


Accuracy Score :  0.8181725056340914


# b. Random Forest Classifier

In [92]:
"""Confusion Matrix and Classification report"""
eval_model(y_test,ypredRFC)


Confusion Matrix : 
 [[6959  446]
 [ 900 1457]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.89      0.94      0.91      7405
           1       0.77      0.62      0.68      2357

    accuracy                           0.86      9762
   macro avg       0.83      0.78      0.80      9762
weighted avg       0.86      0.86      0.86      9762


Accuracy Score :  0.8621184183568941


# c. Logistic Regression

In [93]:
"""Confusion Matrix and Classification report"""
eval_model(y_test,ypredLR)


Confusion Matrix : 
 [[6958  447]
 [1258 1099]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.85      0.94      0.89      7405
           1       0.71      0.47      0.56      2357

    accuracy                           0.83      9762
   macro avg       0.78      0.70      0.73      9762
weighted avg       0.81      0.83      0.81      9762


Accuracy Score :  0.8253431673837328


# d. KNN Classifier

In [94]:
"""Confusion Matrix and Classification report"""
eval_model(y_test,ypredKNN)


Confusion Matrix : 
 [[7132  273]
 [1761  596]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.80      0.96      0.88      7405
           1       0.69      0.25      0.37      2357

    accuracy                           0.79      9762
   macro avg       0.74      0.61      0.62      9762
weighted avg       0.77      0.79      0.75      9762


Accuracy Score :  0.791641057160418


# e. SVC Classifier (with linear kernel)

In [95]:
"""Confusion Matrix and Classification report"""
eval_model(y1_test,ypredSVM)


Confusion Matrix : 
 [[18883   863]
 [ 4459  1825]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.81      0.96      0.88     19746
           1       0.68      0.29      0.41      6284

    accuracy                           0.80     26030
   macro avg       0.74      0.62      0.64     26030
weighted avg       0.78      0.80      0.76     26030


Accuracy Score :  0.7955436035343834


# 7) Validating the result for Precision, Recall, F1-score and Accuracy for each model based on values from confusion_matrix and classification_report.

# a. Decision Tree

In [96]:
print(classification_report(y_test,ypredDTC))
x=confusion_matrix(y_test,ypredDTC)
TP=x[0][0]
TN=x[1][1]
FP=x[1][0]
FN=x[0][1]

PrecisionDTC_0 = TP/(TP+FP)

RecallDTC_0 = TP/(TP+FN)

F1ScoreDTC_0 = (2*PrecisionDTC_0*RecallDTC_0)/(PrecisionDTC_0+RecallDTC_0)

PrecisionDTC_1 = TN/(TN+FN)

RecallDTC_1 = TN/(TN+FP)

F1ScoreDTC_1 = (2*PrecisionDTC_1*RecallDTC_1)/(PrecisionDTC_1+RecallDTC_1)

AccuracyDTC = (TP+TN)/(TP+TN+FP+FN)

print("Precision '0' for Decision Tree",PrecisionDTC_0)
print("Recall    '0' for Decision Tree",RecallDTC_0)
print("F1Score   '0' for Decision Tree",F1ScoreDTC_0)
print("Precision '1' for Decision Tree",PrecisionDTC_1)
print("Recall    '1' for Decision Tree",RecallDTC_1)
print("F1Score   '1' for Decision Tree",F1ScoreDTC_1)
print("Accuracy for Decision Tree",AccuracyDTC)


              precision    recall  f1-score   support

           0       0.87      0.89      0.88      7405
           1       0.63      0.58      0.61      2357

    accuracy                           0.82      9762
   macro avg       0.75      0.74      0.74      9762
weighted avg       0.81      0.82      0.82      9762

Precision '0' for Decision Tree 0.870980495519241
Recall    '0' for Decision Tree 0.8925050641458474
F1Score   '0' for Decision Tree 0.8816114186620424
Precision '1' for Decision Tree 0.6338546458141674
Recall    '1' for Decision Tree 0.5846414934238439
F1Score   '1' for Decision Tree 0.6082542485102626
Accuracy for Decision Tree 0.8181725056340914


# b. Random Forest Classifier

In [97]:
print(classification_report(y_test,ypredRFC))
x=confusion_matrix(y_test,ypredRFC)
TP=x[0][0]
TN=x[1][1]
FP=x[1][0]
FN=x[0][1]

PrecisionRFC_0 = TP/(TP+FP)

RecallRFC_0 = TP/(TP+FN)

F1ScoreRFC_0 = (2*PrecisionRFC_0*RecallRFC_0)/(PrecisionRFC_0+RecallRFC_0)

PrecisionRFC_1 = TN/(TN+FN)

RecallRFC_1 = TN/(TN+FP)

F1ScoreRFC_1 = (2*PrecisionRFC_1*RecallRFC_1)/(PrecisionRFC_1+RecallRFC_1)

AccuracyRFC = (TP+TN)/(TP+TN+FP+FN)

print("Precision '0' for Random Forest Classifier",PrecisionRFC_0)
print("Recall    '0' for Random Forest Classifier",RecallRFC_0)
print("F1Score   '0' for Random Forest Classifier",F1ScoreRFC_0)
print("Precision '1' for Random Forest Classifier",PrecisionRFC_1)
print("Recall    '1' for Random Forest Classifier",RecallRFC_1)
print("F1Score   '1' for Random Forest Classifier",F1ScoreRFC_1)
print("Accuracy for Random Forest Classifier",AccuracyRFC)


              precision    recall  f1-score   support

           0       0.89      0.94      0.91      7405
           1       0.77      0.62      0.68      2357

    accuracy                           0.86      9762
   macro avg       0.83      0.78      0.80      9762
weighted avg       0.86      0.86      0.86      9762

Precision '0' for Random Forest Classifier 0.8854816134368241
Recall    '0' for Random Forest Classifier 0.9397704253882512
F1Score   '0' for Random Forest Classifier 0.9118186582809225
Precision '1' for Random Forest Classifier 0.765633210719916
Recall    '1' for Random Forest Classifier 0.6181586762834111
F1Score   '1' for Random Forest Classifier 0.684037558685446
Accuracy for Random Forest Classifier 0.8621184183568941


# c. Logistic Regression

In [98]:
print(classification_report(y_test,ypredLR))
x=confusion_matrix(y_test,ypredLR)
TP=x[0][0]
TN=x[1][1]
FP=x[1][0]
FN=x[0][1]

PrecisionLR_0 = TP/(TP+FP)

RecallLR_0 = TP/(TP+FN)

F1ScoreLR_0 = (2*PrecisionLR_0*RecallLR_0)/(PrecisionLR_0+RecallLR_0)

PrecisionLR_1 = TN/(TN+FN)

RecallLR_1 = TN/(TN+FP)

F1ScoreLR_1 = (2*PrecisionLR_1*RecallLR_1)/(PrecisionLR_1+RecallLR_1)

AccuracyLR = (TP+TN)/(TP+TN+FP+FN)

print("Precision '0' for Logistic Rrgression",PrecisionLR_0)
print("Recall    '0' for Logistic Rrgression",RecallLR_0)
print("F1Score   '0' for Logistic Rrgression",F1ScoreLR_0)
print("Precision '1' for Logistic Rrgression",PrecisionLR_1)
print("Recall    '1' for Logistic Rrgression",RecallLR_1)
print("F1Score   '1' for Logistic Rrgression",F1ScoreLR_1)
print("Accuracy for Logistic Rrgression",AccuracyLR)


              precision    recall  f1-score   support

           0       0.85      0.94      0.89      7405
           1       0.71      0.47      0.56      2357

    accuracy                           0.83      9762
   macro avg       0.78      0.70      0.73      9762
weighted avg       0.81      0.83      0.81      9762

Precision '0' for Logistic Rrgression 0.8468841285296982
Recall    '0' for Logistic Rrgression 0.9396353814989872
F1Score   '0' for Logistic Rrgression 0.8908520581268806
Precision '1' for Logistic Rrgression 0.7108667529107374
Recall    '1' for Logistic Rrgression 0.46627068307170133
F1Score   '1' for Logistic Rrgression 0.5631565462464772
Accuracy for Logistic Rrgression 0.8253431673837328


# d. KNN Classifier

In [99]:
print(classification_report(y_test,ypredKNN))
x=confusion_matrix(y_test,ypredKNN)
TP=x[0][0]
TN=x[1][1]
FP=x[1][0]
FN=x[0][1]

PrecisionKNN_0 = TP/(TP+FP)

RecallKNN_0 = TP/(TP+FN)

F1ScoreKNN_0 = (2*PrecisionKNN_0*RecallKNN_0)/(PrecisionKNN_0+RecallKNN_0)

PrecisionKNN_1 = TN/(TN+FN)

RecallKNN_1 = TN/(TN+FP)

F1ScoreKNN_1 = (2*PrecisionKNN_1*RecallKNN_1)/(PrecisionKNN_1+RecallKNN_1)

AccuracyKNN = (TP+TN)/(TP+TN+FP+FN)

print("Precision '0' for KNN Classifier",PrecisionKNN_0)
print("Recall    '0' for KNN Classifier",RecallKNN_0)
print("F1Score   '0' for KNN Classifier",F1ScoreKNN_0)
print("Precision '1' for KNN Classifier",PrecisionKNN_1)
print("Recall    '1' for KNN Classifier",RecallKNN_1)
print("F1Score   '1' for KNN Classifier",F1ScoreKNN_1)
print("Accuracy for KNN Classifier",AccuracyKNN)


              precision    recall  f1-score   support

           0       0.80      0.96      0.88      7405
           1       0.69      0.25      0.37      2357

    accuracy                           0.79      9762
   macro avg       0.74      0.61      0.62      9762
weighted avg       0.77      0.79      0.75      9762

Precision '0' for KNN Classifier 0.8019790846733386
Recall    '0' for KNN Classifier 0.963133018230925
F1Score   '0' for KNN Classifier 0.8751994109706712
Precision '1' for KNN Classifier 0.6858457997698504
Recall    '1' for KNN Classifier 0.25286380992787444
F1Score   '1' for KNN Classifier 0.3694978301301922
Accuracy for KNN Classifier 0.791641057160418


# e. SVC Classifier (with linear kernel)

In [100]:
print(classification_report(y1_test,ypredSVM))
x=confusion_matrix(y1_test,ypredSVM)
TP=x[0][0]
TN=x[1][1]
FP=x[1][0]
FN=x[0][1]

PrecisionSVM_0 = TP/(TP+FP)

RecallSVM_0 = TP/(TP+FN)

F1ScoreSVM_0 = (2*PrecisionSVM_0*RecallSVM_0)/(PrecisionSVM_0+RecallSVM_0)

PrecisionSVM_1 = TN/(TN+FN)

RecallSVM_1 = TN/(TN+FP)

F1ScoreSVM_1 = (2*PrecisionSVM_1*RecallSVM_1)/(PrecisionSVM_1+RecallSVM_1)

AccuracySVM = (TP+TN)/(TP+TN+FP+FN)

print("Precision '0' for SVC Classifier",PrecisionSVM_0)
print("Recall    '0' for SVC Classifier",RecallSVM_0)
print("F1Score   '0' for SVC Classifier",F1ScoreSVM_0)
print("Precision '1' for SVC Classifier",PrecisionSVM_1)
print("Recall    '1' for SVC Classifier",RecallSVM_1)
print("F1Score   '1' for SVC Classifier",F1ScoreSVM_1)
print("Accuracy for SVC Classifier",AccuracySVM)


              precision    recall  f1-score   support

           0       0.81      0.96      0.88     19746
           1       0.68      0.29      0.41      6284

    accuracy                           0.80     26030
   macro avg       0.74      0.62      0.64     26030
weighted avg       0.78      0.80      0.76     26030

Precision '0' for SVC Classifier 0.8089709536457887
Recall    '0' for SVC Classifier 0.95629494581181
F1Score   '0' for SVC Classifier 0.8764853323431118
Precision '1' for SVC Classifier 0.6789434523809523
Recall    '1' for SVC Classifier 0.29042011457670275
F1Score   '1' for SVC Classifier 0.40682122157824346
Accuracy for SVC Classifier 0.7955436035343834


# 8) Generating the percentage of misclassification in each of these models.

# a. Decision Tree

In [101]:
Confusion_matrix_DTC = confusion_matrix(y_test, ypredDTC)

Diagonal_sum_DTC = np.trace(Confusion_matrix_DTC)

Total_sum_DTC = np.sum(Confusion_matrix_DTC)

Accuracy_DTC = (Diagonal_sum_DTC/Total_sum_DTC)*100

misclassification_of_DTC = 100 - Accuracy_DTC

print("Misclassification percentage of Decision Tree Classifier:",misclassification_of_DTC,"%")


Misclassification percentage of Decision Tree Classifier: 18.182749436590868 %


# b. Random Forest Classifier

In [102]:
Confusion_matrix_RFC = confusion_matrix(y_test, ypredRFC)

Diagonal_sum_RFC = np.trace(Confusion_matrix_RFC)

Total_sum_RFC = np.sum(Confusion_matrix_RFC)

Accuracy_RFC = (Diagonal_sum_RFC/Total_sum_RFC)*100

misclassification_of_RFC = 100 - Accuracy_RFC

print("Misclassification percentage of Random Forest Classifier :",misclassification_of_RFC,"%")


Misclassification percentage of Random Forest Classifier : 13.788158164310587 %


# c. Logistic Regression

In [103]:
Confusion_matrix_LR = confusion_matrix(y_test, ypredLR)

Diagonal_sum_LR = np.trace(Confusion_matrix_LR)

Total_sum_LR = np.sum(Confusion_matrix_LR)

Accuracy_LR = (Diagonal_sum_LR/Total_sum_LR)*100

misclassification_of_LR = 100 - Accuracy_LR

print("Misclassification percentage of Logistic Regression :",misclassification_of_LR,"%")


Misclassification percentage of Logistic Regression : 17.465683261626722 %


# d. KNN Classifier

In [104]:
Confusion_matrix_KNN = confusion_matrix(y_test, ypredKNN)

Diagonal_sum_KNN = np.trace(Confusion_matrix_KNN)

Total_sum_KNN = np.sum(Confusion_matrix_KNN)

Accuracy_KNN = (Diagonal_sum_KNN/Total_sum_KNN)*100

misclassification_of_KNN = 100 - Accuracy_KNN

print("Misclassification percentage of KNN Classifier :",misclassification_of_KNN,"%")


Misclassification percentage of KNN Classifier : 20.835894283958197 %


# e. SVC Classifier (with linear kernel)

In [105]:
Confusion_matrix_SVM = confusion_matrix(y1_test, ypredSVM)

Diagonal_sum_SVM = np.trace(Confusion_matrix_SVM)

Total_sum_SVM = np.sum(Confusion_matrix_SVM)

Accuracy_SVM = (Diagonal_sum_SVM/Total_sum_SVM)*100

misclassification_of_SVM = 100 - Accuracy_SVM

print("Misclassification percentage of SVC Classifier :",misclassification_of_SVM,"%")


Misclassification percentage of SVC Classifier : 20.44563964656166 %


# 9)Report the model with the best accuracy.

In [106]:
print("\nAccuracy Score of Decision Tree classifier : ",accuracy_score(y_test,ypredDTC),"->",accuracy_score(y_test,ypredDTC)*100,"%")
print("\nAccuracy Score of Random Forest Classifier : ",accuracy_score(y_test,ypredRFC),"->",accuracy_score(y_test,ypredRFC)*100,"%")
print("\nAccuracy Score of KNN Classifier           : ",accuracy_score(y_test,ypredKNN),"->",accuracy_score(y_test,ypredKNN)*100,"%")
print("\nAccuracy Score of Logistic Regression      : ",accuracy_score(y_test,ypredLR),"->",accuracy_score(y_test,ypredLR)*100,"%")
print("\nAccuracy Score of SVM Classifier           : ",accuracy_score(y1_test,ypredSVM),"->",accuracy_score(y1_test,ypredSVM)*100,"%")


Accuracy Score of Decision Tree classifier :  0.8181725056340914 -> 81.81725056340913 %

Accuracy Score of Random Forest Classifier :  0.8621184183568941 -> 86.21184183568941 %

Accuracy Score of KNN Classifier           :  0.791641057160418 -> 79.1641057160418 %

Accuracy Score of Logistic Regression      :  0.8253431673837328 -> 82.53431673837328 %

Accuracy Score of SVM Classifier           :  0.7955436035343834 -> 79.55436035343834 %


# """From the above obesrvations we can conclude that The Model with the Best Accuracy is Random Forest Classifier Model with 86.33% Accuracy """